export const countries = [
  { name: "Afghanistan", isoCode: "AF", phoneCode: "+93", value: "Afghanistan" },
  { name: "Albania", isoCode: "AL", phoneCode: "+355", value: "Albania" },
  { name: "Algeria", isoCode: "DZ", phoneCode: "+213", value: "Algeria" },
  { name: "Andorra", isoCode: "AD", phoneCode: "+376", value: "Andorra" },
  { name: "Angola", isoCode: "AO", phoneCode: "+244", value: "Angola" },
  { name: "Antigua and Barbuda", isoCode: "AG", phoneCode: "+1-268", value: "Antigua and Barbuda" },
  { name: "Argentina", isoCode: "AR", phoneCode: "+54", value: "Argentina" },
  { name: "Armenia", isoCode: "AM", phoneCode: "+374", value: "Armenia" },
  { name: "Australia", isoCode: "AU", phoneCode: "+61", value: "Australia" },
  { name: "Austria", isoCode: "AT", phoneCode: "+43", value: "Austria" },
  { name: "Azerbaijan", isoCode: "AZ", phoneCode: "+994", value: "Azerbaijan" },
  { name: "Bahamas", isoCode: "BS", phoneCode: "+1-242", value: "Bahamas" },
  { name: "Bahrain", isoCode: "BH", phoneCode: "+973", value: "Bahrain" },
  { name: "Bangladesh", isoCode: "BD", phoneCode: "+880", value: "Bangladesh" },
  { name: "Barbados", isoCode: "BB", phoneCode: "+1-246", value: "Barbados" },
  { name: "Belarus", isoCode: "BY", phoneCode: "+375", value: "Belarus" },
  { name: "Belgium", isoCode: "BE", phoneCode: "+32", value: "Belgium" },
  { name: "Belize", isoCode: "BZ", phoneCode: "+501", value: "Belize" },
  { name: "Benin", isoCode: "BJ", phoneCode: "+229", value: "Benin" },
  { name: "Bhutan", isoCode: "BT", phoneCode: "+975", value: "Bhutan" },
  { name: "Bolivia", isoCode: "BO", phoneCode: "+591", value: "Bolivia" },
  { name: "Bosnia and Herzegovina", isoCode: "BA", phoneCode: "+387", value: "Bosnia and Herzegovina" },
  { name: "Botswana", isoCode: "BW", phoneCode: "+267", value: "Botswana" },
  { name: "Brazil", isoCode: "BR", phoneCode: "+55", value: "Brazil" },
  { name: "Brunei", isoCode: "BN", phoneCode: "+673", value: "Brunei" },
  { name: "Bulgaria", isoCode: "BG", phoneCode: "+359", value: "Bulgaria" },
  { name: "Burkina Faso", isoCode: "BF", phoneCode: "+226", value: "Burkina Faso" },
  { name: "Burundi", isoCode: "BI", phoneCode: "+257", value: "Burundi" },
  { name: "Cabo Verde", isoCode: "CV", phoneCode: "+238", value: "Cabo Verde" },
  { name: "Cambodia", isoCode: "KH", phoneCode: "+855", value: "Cambodia" },
  { name: "Cameroon", isoCode: "CM", phoneCode: "+237", value: "Cameroon" },
  { name: "Canada", isoCode: "CA", phoneCode: "+1", value: "Canada" },
  { name: "Central African Republic", isoCode: "CF", phoneCode: "+236", value: "Central African Republic" },
  { name: "Chad", isoCode: "TD", phoneCode: "+235", value: "Chad" },
  { name: "Chile", isoCode: "CL", phoneCode: "+56", value: "Chile" },
  { name: "China", isoCode: "CN", phoneCode: "+86", value: "China" },
  { name: "Colombia", isoCode: "CO", phoneCode: "+57", value: "Colombia" },
  { name: "Comoros", isoCode: "KM", phoneCode: "+269", value: "Comoros" },
  { name: "Congo (Congo-Brazzaville)", isoCode: "CG", phoneCode: "+242", value: "Congo (Congo-Brazzaville)" },
  { name: "Costa Rica", isoCode: "CR", phoneCode: "+506", value: "Costa Rica" },
  { name: "Croatia", isoCode: "HR", phoneCode: "+385", value: "Croatia" },
  { name: "Cuba", isoCode: "CU", phoneCode: "+53", value: "Cuba" },
  { name: "Cyprus", isoCode: "CY", phoneCode: "+357", value: "Cyprus" },
  { name: "Czech Republic", isoCode: "CZ", phoneCode: "+420", value: "Czech Republic" },
  { name: "Democratic Republic of the Congo", isoCode: "CD", phoneCode: "+243", value: "Democratic Republic of the Congo" },
  { name: "Denmark", isoCode: "DK", phoneCode: "+45", value: "Denmark" },
  { name: "Djibouti", isoCode: "DJ", phoneCode: "+253", value: "Djibouti" },
  { name: "Dominica", isoCode: "DM", phoneCode: "+1-767", value: "Dominica" },
  { name: "Dominican Republic", isoCode: "DO", phoneCode: "+1-809", value: "Dominican Republic" },
  { name: "Ecuador", isoCode: "EC", phoneCode: "+593", value: "Ecuador" },
  { name: "Egypt", isoCode: "EG", phoneCode: "+20", value: "Egypt" },
  { name: "El Salvador", isoCode: "SV", phoneCode: "+503", value: "El Salvador" },
  { name: "Equatorial Guinea", isoCode: "GQ", phoneCode: "+240", value: "Equatorial Guinea" },
  { name: "Eritrea", isoCode: "ER", phoneCode: "+291", value: "Eritrea" },
  { name: "Estonia", isoCode: "EE", phoneCode: "+372", value: "Estonia" },
  { name: "Eswatini", isoCode: "SZ", phoneCode: "+268", value: "Eswatini" },
  { name: "Ethiopia", isoCode: "ET", phoneCode: "+251", value: "Ethiopia" },
  { name: "Fiji", isoCode: "FJ", phoneCode: "+679", value: "Fiji" },
  { name: "Finland", isoCode: "FI", phoneCode: "+358", value: "Finland" },
  { name: "France", isoCode: "FR", phoneCode: "+33", value: "France" },
  { name: "Gabon", isoCode: "GA", phoneCode: "+241", value: "Gabon" },
  { name: "Gambia", isoCode: "GM", phoneCode: "+220", value: "Gambia" },
  { name: "Georgia", isoCode: "GE", phoneCode: "+995", value: "Georgia" },
  { name: "Germany", isoCode: "DE", phoneCode: "+49", value: "Germany" },
  { name: "Ghana", isoCode: "GH", phoneCode: "+233", value: "Ghana" },
  { name: "Greece", isoCode: "GR", phoneCode: "+30", value: "Greece" },
  { name: "Grenada", isoCode: "GD", phoneCode: "+1-473", value: "Grenada" },
  { name: "Guatemala", isoCode: "GT", phoneCode: "+502", value: "Guatemala" },
  { name: "Guinea", isoCode: "GN", phoneCode: "+224", value: "Guinea" },
  { name: "Guinea-Bissau", isoCode: "GW", phoneCode: "+245", value: "Guinea-Bissau" },
  { name: "Guyana", isoCode: "GY", phoneCode: "+592", value: "Guyana" },
  { name: "Haiti", isoCode: "HT", phoneCode: "+509", value: "Haiti" },
  { name: "Honduras", isoCode: "HN", phoneCode: "+504", value: "Honduras" },
  { name: "Hungary", isoCode: "HU", phoneCode: "+36", value: "Hungary" },
  { name: "Iceland", isoCode: "IS", phoneCode: "+354", value: "Iceland" },
  { name: "India", isoCode: "IN", phoneCode: "+91", value: "India" },
  { name: "Indonesia", isoCode: "ID", phoneCode: "+62", value: "Indonesia" },
  { name: "Iran", isoCode: "IR", phoneCode: "+98", value: "Iran" },
  { name: "Iraq", isoCode: "IQ", phoneCode: "+964", value: "Iraq" },
  { name: "Ireland", isoCode: "IE", phoneCode: "+353", value: "Ireland" },
  { name: "Israel", isoCode: "IL", phoneCode: "+972", value: "Israel" },
  { name: "Italy", isoCode: "IT", phoneCode: "+39", value: "Italy" },
  { name: "Jamaica", isoCode: "JM", phoneCode: "+1-876", value: "Jamaica" },
  { name: "Japan", isoCode: "JP", phoneCode: "+81", value: "Japan" },
  { name: "Jordan", isoCode: "JO", phoneCode: "+962", value: "Jordan" },
  { name: "Kazakhstan", isoCode: "KZ", phoneCode: "+7", value: "Kazakhstan" },
  { name: "Kenya", isoCode: "KE", phoneCode: "+254", value: "Kenya" },
  { name: "Kiribati", isoCode: "KI", phoneCode: "+686", value: "Kiribati" },
  { name: "Kuwait", isoCode: "KW", phoneCode: "+965", value: "Kuwait" },
  { name: "Kyrgyzstan", isoCode: "KG", phoneCode: "+996", value: "Kyrgyzstan" },
  { name: "Laos", isoCode: "LA", phoneCode: "+856", value: "Laos" },
  { name: "Latvia", isoCode: "LV", phoneCode: "+371", value: "Latvia" },
  { name: "Lebanon", isoCode: "LB", phoneCode: "+961", value: "Lebanon" },
  { name: "Lesotho", isoCode: "LS", phoneCode: "+266", value: "Lesotho" },
  { name: "Liberia", isoCode: "LR", phoneCode: "+231", value: "Liberia" },
  { name: "Libya", isoCode: "LY", phoneCode: "+218", value: "Libya" },
  { name: "Liechtenstein", isoCode: "LI", phoneCode: "+423", value: "Liechtenstein" },
  { name: "Lithuania", isoCode: "LT", phoneCode: "+370", value: "Lithuania" },
  { name: "Luxembourg", isoCode: "LU", phoneCode: "+352", value: "Luxembourg" },
  { name: "Madagascar", isoCode: "MG", phoneCode: "+261", value: "Madagascar" },
  { name: "Malawi", isoCode: "MW", phoneCode: "+265", value: "Malawi" },
  { name: "Malaysia", isoCode: "MY", phoneCode: "+60", value: "Malaysia" },
  { name: "Maldives", isoCode: "MV", phoneCode: "+960", value: "Maldives" },
  { name: "Mali", isoCode: "ML", phoneCode: "+223", value: "Mali" },
  { name: "Malta", isoCode: "MT", phoneCode: "+356", value: "Malta" },
  { name: "Marshall Islands", isoCode: "MH", phoneCode: "+692", value: "Marshall Islands" },
  { name: "Mauritania", isoCode: "MR", phoneCode: "+222", value: "Mauritania" },
  { name: "Mauritius", isoCode: "MU", phoneCode: "+230", value: "Mauritius" },
  { name: "Mexico", isoCode: "MX", phoneCode: "+52", value: "Mexico" },
  { name: "Micronesia", isoCode: "FM", phoneCode: "+691", value: "Micronesia" },
  { name: "Moldova", isoCode: "MD", phoneCode: "+373", value: "Moldova" },
  { name: "Monaco", isoCode: "MC", phoneCode: "+377", value: "Monaco" },
  { name: "Mongolia", isoCode: "MN", phoneCode: "+976", value: "Mongolia" },
  { name: "Montenegro", isoCode: "ME", phoneCode: "+382", value: "Montenegro" },
  { name: "Morocco", isoCode: "MA", phoneCode: "+212", value: "Morocco" },
  { name: "Mozambique", isoCode: "MZ", phoneCode: "+258", value: "Mozambique" },
  { name: "Myanmar (Burma)", isoCode: "MM", phoneCode: "+95", value: "Myanmar (Burma)" },
  { name: "Namibia", isoCode: "NA", phoneCode: "+264", value: "Namibia" },
  { name: "Nauru", isoCode: "NR", phoneCode: "+674", value: "Nauru" },
  { name: "Nepal", isoCode: "NP", phoneCode: "+977", value: "Nepal" },
  { name: "Netherlands", isoCode: "NL", phoneCode: "+31", value: "Netherlands" },
  { name: "New Zealand", isoCode: "NZ", phoneCode: "+64", value: "New Zealand" },
  { name: "Nicaragua", isoCode: "NI", phoneCode: "+505", value: "Nicaragua" },
  { name: "Niger", isoCode: "NE", phoneCode: "+227", value: "Niger" },
  { name: "Nigeria", isoCode: "NG", phoneCode: "+234", value: "Nigeria" },
  { name: "North Korea", isoCode: "KP", phoneCode: "+850", value: "North Korea" },
  { name: "North Macedonia", isoCode: "MK", phoneCode: "+389", value: "North Macedonia" },
  { name: "Norway", isoCode: "NO", phoneCode: "+47", value: "Norway" },
  { name: "Oman", isoCode: "OM", phoneCode: "+968", value: "Oman" },
  { name: "Pakistan", isoCode: "PK", phoneCode: "+92", value: "Pakistan" },
  { name: "Palau", isoCode: "PW", phoneCode: "+680", value: "Palau" },
  { name: "Palestine State", isoCode: "PS", phoneCode: "+970", value: "Palestine State" },
  { name: "Panama", isoCode: "PA", phoneCode: "+507", value: "Panama" },
  { name: "Papua New Guinea", isoCode: "PG", phoneCode: "+675", value: "Papua New Guinea" },
  { name: "Paraguay", isoCode: "PY", phoneCode: "+595", value: "Paraguay" },
  { name: "Peru", isoCode: "PE", phoneCode: "+51", value: "Peru" },
  { name: "Philippines", isoCode: "PH", phoneCode: "+63", value: "Philippines" },
  { name: "Poland", isoCode: "PL", phoneCode: "+48", value: "Poland" },
  { name: "Portugal", isoCode: "PT", phoneCode: "+351", value: "Portugal" },
  { name: "Qatar", isoCode: "QA", phoneCode: "+974", value: "Qatar" },
  { name: "Romania", isoCode: "RO", phoneCode: "+40", value: "Romania" },
  { name: "Russia", isoCode: "RU", phoneCode: "+7", value: "Russia" },
  { name: "Rwanda", isoCode: "RW", phoneCode: "+250", value: "Rwanda" },
  { name: "Saint Kitts and Nevis", isoCode: "KN", phoneCode: "+1-869", value: "Saint Kitts and Nevis" },
  { name: "Saint Lucia", isoCode: "LC", phoneCode: "+1-758", value: "Saint Lucia" },
  { name: "Saint Vincent and the Grenadines", isoCode: "VC", phoneCode: "+1-784", value: "Saint Vincent and the Grenadines" },
  { name: "Samoa", isoCode: "WS", phoneCode: "+685", value: "Samoa" },
  { name: "San Marino", isoCode: "SM", phoneCode: "+378", value: "San Marino" },
  { name: "Sao Tome and Principe", isoCode: "ST", phoneCode: "+239", value: "Sao Tome and Principe" },
  { name: "Saudi Arabia", isoCode: "SA", phoneCode: "+966", value: "Saudi Arabia" },
  { name: "Senegal", isoCode: "SN", phoneCode: "+221", value: "Senegal" },
  { name: "Serbia", isoCode: "RS", phoneCode: "+381", value: "Serbia" },
  { name: "Seychelles", isoCode: "SC", phoneCode: "+248", value: "Seychelles" },
  { name: "Sierra Leone", isoCode: "SL", phoneCode: "+232", value: "Sierra Leone" },
  { name: "Singapore", isoCode: "SG", phoneCode: "+65", value: "Singapore" },
  { name: "Slovakia", isoCode: "SK", phoneCode: "+421", value: "Slovakia" },
  { name: "Slovenia", isoCode: "SI", phoneCode: "+386", value: "Slovenia" },
  { name: "Solomon Islands", isoCode: "SB", phoneCode: "+677", value: "Solomon Islands" },
  { name: "Somalia", isoCode: "SO", phoneCode: "+252", value: "Somalia" },
  { name: "South Africa", isoCode: "ZA", phoneCode: "+27", value: "South Africa" },
  { name: "South Korea", isoCode: "KR", phoneCode: "+82", value: "South Korea" },
  { name: "South Sudan", isoCode: "SS", phoneCode: "+211", value: "South Sudan" },
  { name: "Spain", isoCode: "ES", phoneCode: "+34", value: "Spain" },
  { name: "Sri Lanka", isoCode: "LK", phoneCode: "+94", value: "Sri Lanka" },
  { name: "Sudan", isoCode: "SD", phoneCode: "+249", value: "Sudan" },
  { name: "Suriname", isoCode: "SR", phoneCode: "+597", value: "Suriname" },
  { name: "Sweden", isoCode: "SE", phoneCode: "+46", value: "Sweden" },
  { name: "Switzerland", isoCode: "CH", phoneCode: "+41", value: "Switzerland" },
  { name: "Syria", isoCode: "SY", phoneCode: "+963", value: "Syria" },
  { name: "Taiwan", isoCode: "TW", phoneCode: "+886", value: "Taiwan" },
  { name: "Tajikistan", isoCode: "TJ", phoneCode: "+992", value: "Tajikistan" },
  { name: "Tanzania", isoCode: "TZ", phoneCode: "+255", value: "Tanzania" },
  { name: "Thailand", isoCode: "TH", phoneCode: "+66", value: "Thailand" },
  { name: "Timor-Leste", isoCode: "TL", phoneCode: "+670", value: "Timor-Leste" },
  { name: "Togo", isoCode: "TG", phoneCode: "+228", value: "Togo" },
  { name: "Tonga", isoCode: "TO", phoneCode: "+676", value: "Tonga" },
  { name: "Trinidad and Tobago", isoCode: "TT", phoneCode: "+1-868", value: "Trinidad and Tobago" },
  { name: "Tunisia", isoCode: "TN", phoneCode: "+216", value: "Tunisia" },
  { name: "Turkey", isoCode: "TR", phoneCode: "+90", value: "Turkey" },
  { name: "Turkmenistan", isoCode: "TM", phoneCode: "+993", value: "Turkmenistan" },
  { name: "Tuvalu", isoCode: "TV", phoneCode: "+688", value: "Tuvalu" },
  { name: "Uganda", isoCode: "UG", phoneCode: "+256", value: "Uganda" },
  { name: "Ukraine", isoCode: "UA", phoneCode: "+380", value: "Ukraine" },
  { name: "United Arab Emirates", isoCode: "AE", phoneCode: "+971", value: "United Arab Emirates" },
  { name: "United Kingdom", isoCode: "GB", phoneCode: "+44", value: "United Kingdom" },
  { name: "United States of America", isoCode: "US", phoneCode: "+1", value: "United States of America" },
  { name: "Uruguay", isoCode: "UY", phoneCode: "+598", value: "Uruguay" },
  { name: "Uzbekistan", isoCode: "UZ", phoneCode: "+998", value: "Uzbekistan" },
  { name: "Vanuatu", isoCode: "VU", phoneCode: "+678", value: "Vanuatu" },
  { name: "Vatican City", isoCode: "VA", phoneCode: "+379", value: "Vatican City" },
  { name: "Venezuela", isoCode: "VE", phoneCode: "+58", value: "Venezuela" },
  { name: "Vietnam", isoCode: "VN", phoneCode: "+84", value: "Vietnam" },
  { name: "Yemen", isoCode: "YE", phoneCode: "+967", value: "Yemen" },
  { name: "Zambia", isoCode: "ZM", phoneCode: "+260", value: "Zambia" },
  { name: "Zimbabwe", isoCode: "ZW", phoneCode: "+263", value: "Zimbabwe" },
];