export const countries = [
  { name: "Afghanistan", isoCode: "AF", phoneCode: "+93", value: "Afghanistan" },
  { name: "Albania", isoCode: "AL", phoneCode: "+355", value: "Albania" },
  { name: "Algeria", isoCode: "DZ", phoneCode: "+213", value: "Algeria" },
  { name: "Åland Islands", isoCode: "AX", phoneCode: "+358", value: "Åland Islands" },
  { name: "American Samoa", isoCode: "AS", phoneCode: "+1-684", value: "American Samoa" },
  { name: "Andorra", isoCode: "AD", phoneCode: "+376", value: "Andorra" },
  { name: "Angola", isoCode: "AO", phoneCode: "+244", value: "Angola" },
  { name: "Anguilla", isoCode: "AI", phoneCode: "+1-264", value: "Anguilla" },
  { name: "Antigua and Barbuda", isoCode: "AG", phoneCode: "+1-268", value: "Antigua and Barbuda" },
  { name: "Argentina", isoCode: "AR", phoneCode: "+54", value: "Argentina" },
  { name: "Armenia", isoCode: "AM", phoneCode: "+374", value: "Armenia" },
  { name: "Aruba", isoCode: "AW", phoneCode: "+297", value: "Aruba" },
  { name: "Antarctica", isoCode: "AQ", phoneCode: "+672", value: "Antarctica" },
  { name: "Australia", isoCode: "AU", phoneCode: "+61", value: "Australia" },
  { name: "Austria", isoCode: "AT", phoneCode: "+43", value: "Austria" },
  { name: "Azerbaijan", isoCode: "AZ", phoneCode: "+994", value: "Azerbaijan" },
  { name: "Bahamas", isoCode: "BS", phoneCode: "+1-242", value: "Bahamas" },
  { name: "Bahrain", isoCode: "BH", phoneCode: "+973", value: "Bahrain" },
  { name: "Bangladesh", isoCode: "BD", phoneCode: "+880", value: "Bangladesh" },
  { name: "Barbados", isoCode: "BB", phoneCode: "+1-246", value: "Barbados" },
  { name: "Belarus", isoCode: "BY", phoneCode: "+375", value: "Belarus" },
  { name: "Belgium", isoCode: "BE", phoneCode: "+32", value: "Belgium" },
  { name: "Belize", isoCode: "BZ", phoneCode: "+501", value: "Belize" },
  { name: "Benin", isoCode: "BJ", phoneCode: "+229", value: "Benin" },
  { name: "Bhutan", isoCode: "BT", phoneCode: "+975", value: "Bhutan" },
  { name: "Bolivia (Plurinational State of)", isoCode: "BO", phoneCode: "+591", value: "Bolivia" },
  { name: "Bonaire, Sint Eustatius and Saba", isoCode: "BQ", phoneCode: "+599", value: "Bonaire, Sint Eustatius and Saba" },
  { name: "Bosnia and Herzegovina", isoCode: "BA", phoneCode: "+387", value: "Bosnia and Herzegovina" },
  { name: "Botswana", isoCode: "BW", phoneCode: "+267", value: "Botswana" },
  { name: "Bouvet Island", isoCode: "BV", phoneCode: "+47", value: "Bouvet Island" },
  { name: "Brazil", isoCode: "BR", phoneCode: "+55", value: "Brazil" },
  { name: "Brunei Darussalam", isoCode: "BN", phoneCode: "+673", value: "Brunei Darussalam" },
  { name: "Bulgaria", isoCode: "BG", phoneCode: "+359", value: "Bulgaria" },
  { name: "Burundi", isoCode: "BI", phoneCode: "+257", value: "Burundi" },
  { name: "Burkina Faso", isoCode: "BF", phoneCode: "+226", value: "Burkina Faso" },
  { name: "Cambodia", isoCode: "KH", phoneCode: "+855", value: "Cambodia" },
  { name: "Cameroon", isoCode: "CM", phoneCode: "+237", value: "Cameroon" },
  { name: "Canada", isoCode: "CA", phoneCode: "+1", value: "Canada" },
  { name: "Central African Republic", isoCode: "CF", phoneCode: "+236", value: "Central African Republic" },
  { name: "Chile", isoCode: "CL", phoneCode: "+56", value: "Chile" },
  { name: "China", isoCode: "CN", phoneCode: "+86", value: "China" },
  { name: "Cocos (Keeling) Islands", isoCode: "CC", phoneCode: "+61", value: "Cocos (Keeling) Islands" },
  { name: "Colombia", isoCode: "CO", phoneCode: "+57", value: "Colombia" },
  { name: "Congo", isoCode: "CG", phoneCode: "+242", value: "Congo" },
  { name: "Congo (Democratic Republic of the)", isoCode: "CD", phoneCode: "+243", value: "Congo (Democratic Republic of the)" },
  { name: "Costa Rica", isoCode: "CR", phoneCode: "+506", value: "Costa Rica" },
  { name: "Croatia", isoCode: "HR", phoneCode: "+385", value: "Croatia" },
  { name: "Cuba", isoCode: "CU", phoneCode: "+53", value: "Cuba" },
  { name: "Cyprus", isoCode: "CY", phoneCode: "+357", value: "Cyprus" },
  { name: "Czech Republic", isoCode: "CZ", phoneCode: "+420", value: "Czech Republic" },
  { name: "Côte d’Ivoire", isoCode: "CI", phoneCode: "+225", value: "Côte d’Ivoire" },
  { name: "Denmark", isoCode: "DK", phoneCode: "+45", value: "Denmark" },
  { name: "Egypt", isoCode: "EG", phoneCode: "+20", value: "Egypt" },
  { name: "Finland", isoCode: "FI", phoneCode: "+358", value: "Finland" },
  { name: "France", isoCode: "FR", phoneCode: "+33", value: "France" },
  { name: "French Southern Territories", isoCode: "TF", phoneCode: "+262", value: "French Southern Territories" },
  { name: "Germany", isoCode: "DE", phoneCode: "+49", value: "Germany" },
  { name: "Greece", isoCode: "GR", phoneCode: "+30", value: "Greece" },
  { name: "Hong Kong", isoCode: "HK", phoneCode: "+852", value: "Hong Kong" },
  { name: "Hungary", isoCode: "HU", phoneCode: "+36", value: "Hungary" },
  { name: "Iceland", isoCode: "IS", phoneCode: "+354", value: "Iceland" },
  { name: "India", isoCode: "IN", phoneCode: "+91", value: "India" },
  { name: "Indonesia", isoCode: "ID", phoneCode: "+62", value: "Indonesia" },
  { name: "Iran", isoCode: "IR", phoneCode: "+98", value: "Iran" },
  { name: "Iraq", isoCode: "IQ", phoneCode: "+964", value: "Iraq" },
  { name: "Ireland", isoCode: "IE", phoneCode: "+353", value: "Ireland" },
  { name: "Israel", isoCode: "IL", phoneCode: "+972", value: "Israel" },
  { name: "Italy", isoCode: "IT", phoneCode: "+39", value: "Italy" },
  { name: "Japan", isoCode: "JP", phoneCode: "+81", value: "Japan" },
  { name: "Kenya", isoCode: "KE", phoneCode: "+254", value: "Kenya" },
  { name: "Kuwait", isoCode: "KW", phoneCode: "+965", value: "Kuwait" },
  { name: "Malaysia", isoCode: "MY", phoneCode: "+60", value: "Malaysia" },
  { name: "Maldives", isoCode: "MV", phoneCode: "+960", value: "Maldives" },
  { name: "Mexico", isoCode: "MX", phoneCode: "+52", value: "Mexico" },
  { name: "Nepal", isoCode: "NP", phoneCode: "+977", value: "Nepal" },
  { name: "Netherlands", isoCode: "NL", phoneCode: "+31", value: "Netherlands" },
  { name: "New Zealand", isoCode: "NZ", phoneCode: "+64", value: "New Zealand" },
  { name: "Nigeria", isoCode: "NG", phoneCode: "+234", value: "Nigeria" },
  { name: "Norway", isoCode: "NO", phoneCode: "+47", value: "Norway" },
  { name: "Oman", isoCode: "OM", phoneCode: "+968", value: "Oman" },
  { name: "Pakistan", isoCode: "PK", phoneCode: "+92", value: "Pakistan" },
  { name: "Philippines", isoCode: "PH", phoneCode: "+63", value: "Philippines" },
  { name: "Poland", isoCode: "PL", phoneCode: "+48", value: "Poland" },
  { name: "Portugal", isoCode: "PT", phoneCode: "+351", value: "Portugal" },
  { name: "Qatar", isoCode: "QA", phoneCode: "+974", value: "Qatar" },
  { name: "Russia", isoCode: "RU", phoneCode: "+7", value: "Russia" },
  { name: "Saudi Arabia", isoCode: "SA", phoneCode: "+966", value: "Saudi Arabia" },
  { name: "Singapore", isoCode: "SG", phoneCode: "+65", value: "Singapore" },
  { name: "South Africa", isoCode: "ZA", phoneCode: "+27", value: "South Africa" },
  { name: "South Korea", isoCode: "KR", phoneCode: "+82", value: "South Korea" },
  { name: "Spain", isoCode: "ES", phoneCode: "+34", value: "Spain" },
  { name: "Sri Lanka", isoCode: "LK", phoneCode: "+94", value: "Sri Lanka" },
  { name: "Sweden", isoCode: "SE", phoneCode: "+46", value: "Sweden" },
  { name: "Switzerland", isoCode: "CH", phoneCode: "+41", value: "Switzerland" },
  { name: "Taiwan", isoCode: "TW", phoneCode: "+886", value: "Taiwan" },
  { name: "Thailand", isoCode: "TH", phoneCode: "+66", value: "Thailand" },
  { name: "Turkey", isoCode: "TR", phoneCode: "+90", value: "Turkey" },
  { name: "Ukraine", isoCode: "UA", phoneCode: "+380", value: "Ukraine" },
  { name: "United Arab Emirates", isoCode: "AE", phoneCode: "+971", value: "United Arab Emirates" },
  { name: "United Kingdom", isoCode: "GB", phoneCode: "+44", value: "United Kingdom" },
  { name: "United States", isoCode: "US", phoneCode: "+1", value: "United States" },
  { name: "Vietnam", isoCode: "VN", phoneCode: "+84", value: "Vietnam" },
  { name: "Zambia", isoCode: "ZM", phoneCode: "+260", value: "Zambia" },
  { name: "Zimbabwe", isoCode: "ZW", phoneCode: "+263", value: "Zimbabwe" }
];