// export const plans = {
//     'monthly':[
// {
//         id: "free",
//         name: "Free",
//         currency: 'usd',
//         originalPrice: 0,
//         pricePerUser: 0,
//         discount: 0,
//         billing_cycle: false,
//         members_text: 'Free for up to 3 members',
//         features: [
//             "Single Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "free",
//         name: "Free",
//         originalPrice: 0,
//         pricePerUser: 0,
//         discount: 0,
//         billing_cycle: false,
//         members_text: 'Free for up to 3 members',
//         features: [
//             "Single Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1Sm6f9SZtJkrH95eY3adt6dK",
//         name: "Pro",
//         currency: 'inr',
//         originalPrice: 666,
//         pricePerUser: 666,
//         discount: 0,
//         billing_cycle: 'monthly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1T1kMCSZtJkrH95eUTsOzj28",
//         name: "Pro",
//         currency: 'usd',
//         originalPrice: 8,
//         pricePerUser: 8,
//         discount: 0,
//         billing_cycle: 'monthly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1Sm6h8SZtJkrH95eYrwqvWQx",
//         name: "Elite",
//         discount: 0,
//         currency: 'inr',
//         originalPrice: 916,
//         pricePerUser: 916,
//         billing_cycle: 'monthly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Recorded Screen Videos",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1T1kNISZtJkrH95epkJdx2QN",
//         name: "Elite",
//         discount: 0,
//         currency: 'usd',
//         originalPrice: 916,
//         pricePerUser: 12,
//         billing_cycle: 'monthly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Recorded Screen Videos",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     }
//     ],
//     'quarterly':[
    //     {
    //     id: "free",
    //     name: "Free",
    //     currency: 'usd',
    //     originalPrice: 0,
    //     pricePerUser: 0,
    //     discount: 0,
    //     billing_cycle: false,
    //     members_text: 'Free for up to 3 members',
    //     features: [
    //         "Single Workspace",
    //         "Unlimited Projects",
    //         "Unlimited Tasks",
    //         "Unlimited Workflows",
    //         "Time Tracking",
    //         "Live Screen View",
    //         "Screenshots",
    //         "Reports",
    //         "Attendance Tracking"
    //     ],
    // },
//     {
//         id: "free",
//         name: "Free",
//         originalPrice: 0,
//         pricePerUser: 0,
//         discount: 0,
//         billing_cycle: false,
//         members_text: 'Free for up to 3 members',
//         features: [
//             "Single Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1Sm6g9SZtJkrH95efBqhCMs0",
//         name: "Pro",
//         discount: 20,
//         currency: 'inr',
//         originalPrice: 666,
//         pricePerUser: 533,
//         billing_cycle: 'quarterly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1T1kMPSZtJkrH95eTU4yhf2n",
//         name: "Pro",
//         discount: 20,
//         currency: 'usd',
//         originalPrice: 24,
//         pricePerUser: 6.40,
//         billing_cycle: 'quarterly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1Sm6hSSZtJkrH95e3ouAIMxd",
//         name: "Elite",
//         discount: 20,
//         currency: 'inr',
//         originalPrice: 916,
//         pricePerUser: 733,
//         billing_cycle: 'quarterly',
//         members_text: 'Unlimited Team Members',
//         features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Recorded Screen Videos",
//         "Reports",
//         "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1T1kNUSZtJkrH95eeWlP2oMU",
//         name: "Elite",
//         discount: 20,
//         currency: 'usd',
//         originalPrice: 916,
//         pricePerUser: 9.60,
//         billing_cycle: 'quarterly',
//         members_text: 'Unlimited Team Members',
//         features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Recorded Screen Videos",
//         "Reports",
//         "Attendance Tracking"
//         ],
//     }
//     ],
//     'yearly': [
    //     {
    //     id: "free",
    //     name: "Free",
    //     currency: 'usd',
    //     originalPrice: 0,
    //     pricePerUser: 0,
    //     discount: 0,
    //     billing_cycle: false,
    //     members_text: 'Free for up to 3 members',
    //     features: [
    //         "Single Workspace",
    //         "Unlimited Projects",
    //         "Unlimited Tasks",
    //         "Unlimited Workflows",
    //         "Time Tracking",
    //         "Live Screen View",
    //         "Screenshots",
    //         "Reports",
    //         "Attendance Tracking"
    //     ],
    // },
//     {
//         id: "free",
//         name: "Free",
//         pricePerUser: 0,
//         discount: 0,
//         billing_cycle: false,
//         members_text: 'Free for up to 3 members',
//         features: [
//             "Single Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
    
//         id: "price_1Sm6gZSZtJkrH95eBNmdopyx",
//         name: "Pro",
//         discount: 40,
//         currency: 'inr',
//         originalPrice: 666,
//         pricePerUser: 400,
//         billing_cycle: 'yearly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
    
//         id: "price_1T1kMfSZtJkrH95eJecoIR1e",
//         name: "Pro",
//         discount: 40,
//         currency: 'usd',
//         originalPrice: 666,
//         pricePerUser: 4.80,
//         billing_cycle: 'yearly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1Sm6hhSZtJkrH95e3hAKkKBG",
//         name: "Elite",
//         discount: 40,
//         currency: 'inr',
//         originalPrice: 916,
//         pricePerUser: 550,
//         billing_cycle: 'yearly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Recorded Screen Videos",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     },
//     {
//         id: "price_1T1kNhSZtJkrH95eEKKOZ2LG",
//         name: "Elite",
//         discount: 40,
//         currency: 'usd',
//         originalPrice: 916,
//         pricePerUser: 7.20,
//         billing_cycle: 'yearly',
//         members_text: 'Unlimited Team Members',
//         features: [
//             "Unlimited Workspace",
//             "Unlimited Projects",
//             "Unlimited Tasks",
//             "Unlimited Workflows",
//             "Time Tracking",
//             "Live Screen View",
//             "Screenshots",
//             "Recorded Screen Videos",
//             "Reports",
//             "Attendance Tracking"
//         ],
//     }
//     ]
// };

// export const planNames =  {
//     'price_1Sm6f9SZtJkrH95eY3adt6dK': 'Pro',
//     'price_1Sm6g9SZtJkrH95efBqhCMs0': 'Pro',
//     'price_1Sm6gZSZtJkrH95eBNmdopyx': 'Pro',
//     'price_1T1kMCSZtJkrH95eUTsOzj28': 'Pro',
//     'price_1T1kMPSZtJkrH95eTU4yhf2n': 'Pro',
//     'price_1T1kMfSZtJkrH95eJecoIR1e': 'Pro',
//     'price_1Sm6h8SZtJkrH95eYrwqvWQx': 'Elite',
//     'price_1Sm6hhSZtJkrH95e3hAKkKBG': 'Elite',
//     'price_1Sm6hhSZtJkrH95e3hAKkKBG': 'Elite',
//     'price_1T1kNISZtJkrH95epkJdx2QN': 'Elite',
//     'price_1T1kNUSZtJkrH95eeWlP2oMU': 'Elite',
//     'price_1T1kNhSZtJkrH95eEKKOZ2LG': 'Elite',
//     'free': 'Free',
//     'trial': 'Trial'
// }

// export const planPrices =  {
//     'price_1Sm6f9SZtJkrH95eY3adt6dK': 66600,
//     'price_1Sm6g9SZtJkrH95efBqhCMs0': 53300,
//     'price_1Sm6gZSZtJkrH95eBNmdopyx': 40000,
//     'price_1T1kMCSZtJkrH95eUTsOzj28': 800,
//     'price_1T1kMPSZtJkrH95eTU4yhf2n': 640,
//     'price_1T1kMfSZtJkrH95eJecoIR1e': 480,

//     'price_1Sm6h8SZtJkrH95eYrwqvWQx': 91600,
//     'price_1Sm6hhSZtJkrH95e3hAKkKBG': 55000,
//     'price_1Sm6hhSZtJkrH95e3hAKkKBG': 73300,
//     'price_1T1kNISZtJkrH95epkJdx2QN': 1200,
//     'price_1T1kNUSZtJkrH95eeWlP2oMU': 960,
//     'price_1T1kNhSZtJkrH95eEKKOZ2LG': 720,
//     'free': 0,
//     'trial': 0
// }


export const plans = {
    'monthly':[
    {
        id: "free",
        name: "Free",
        currency: 'inr',
        originalPrice: 0,
        pricePerUser: 0,
        discount: 0,
        billing_cycle: false,
        members_text: 'Free for up to 3 members',
        features: [
            "Single Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "free",
        name: "Free",
        currency: 'usd',
        originalPrice: 0,
        pricePerUser: 0,
        discount: 0,
        billing_cycle: false,
        members_text: 'Free for up to 3 members',
        features: [
            "Single Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kHASZtJkrH95eQL9A6yDo",
        name: "Pro",
        currency: 'inr',
        originalPrice: 666,
        pricePerUser: 666,
        discount: 0,
        billing_cycle: 'monthly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kI7SZtJkrH95e0GJmug6u",
        name: "Pro",
        currency: 'usd',
        originalPrice: 8,
        pricePerUser: 8,
        discount: 0,
        billing_cycle: 'monthly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kKxSZtJkrH95e14uVND57",
        name: "Elite",
        discount: 0,
        currency: 'inr',
        originalPrice: 916,
        pricePerUser: 916,
        billing_cycle: 'monthly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Recorded Screen Videos",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kKxSZtJkrH95ehbhfAbCK",
        name: "Elite",
        discount: 0,
        currency: 'usd',
        originalPrice: 916,
        pricePerUser: 12,
        billing_cycle: 'monthly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Recorded Screen Videos",
            "Reports",
            "Attendance Tracking"
        ],
    }
    ],
    'quarterly':[
        {
        id: "free",
        name: "Free",
        currency: 'usd',
        originalPrice: 0,
        pricePerUser: 0,
        discount: 0,
        billing_cycle: false,
        members_text: 'Free for up to 3 members',
        features: [
            "Single Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "free",
        name: "Free",
        originalPrice: 0,
        pricePerUser: 0,
        currency: 'inr',
        discount: 0,
        billing_cycle: false,
        members_text: 'Free for up to 3 members',
        features: [
            "Single Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kHcSZtJkrH95eh134b9bb",
        name: "Pro",
        discount: 20,
        currency: 'inr',
        originalPrice: 666,
        pricePerUser: 533,
        billing_cycle: 'quarterly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kIPSZtJkrH95eeutEK3Ju",
        name: "Pro",
        discount: 20,
        currency: 'usd',
        originalPrice: 24,
        pricePerUser: 6.40,
        billing_cycle: 'quarterly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kKxSZtJkrH95etWdAjHqI",
        name: "Elite",
        discount: 20,
        currency: 'inr',
        originalPrice: 916,
        pricePerUser: 733,
        billing_cycle: 'quarterly',
        members_text: 'Unlimited Team Members',
        features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Recorded Screen Videos",
        "Reports",
        "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kKxSZtJkrH95e27mYWXim",
        name: "Elite",
        discount: 20,
        currency: 'usd',
        originalPrice: 916,
        pricePerUser: 9.60,
        billing_cycle: 'quarterly',
        members_text: 'Unlimited Team Members',
        features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Recorded Screen Videos",
        "Reports",
        "Attendance Tracking"
        ],
    }
    ],
    'yearly': [
        {
        id: "free",
        name: "Free",
        currency: 'usd',
        originalPrice: 0,
        pricePerUser: 0,
        discount: 0,
        billing_cycle: false,
        members_text: 'Free for up to 3 members',
        features: [
            "Single Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "free",
        name: "Free",
        pricePerUser: 0,
        currency: 'inr',
        discount: 0,
        billing_cycle: false,
        members_text: 'Free for up to 3 members',
        features: [
            "Single Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
    
        id: "price_1T1kHsSZtJkrH95en1y7PPEF",
        name: "Pro",
        discount: 40,
        currency: 'inr',
        originalPrice: 666,
        pricePerUser: 400,
        billing_cycle: 'yearly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
    
        id: "price_1T1kIlSZtJkrH95eQ5T5a2OD",
        name: "Pro",
        discount: 40,
        currency: 'usd',
        originalPrice: 666,
        pricePerUser: 4.80,
        billing_cycle: 'yearly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kKxSZtJkrH95eJMnYM4aa",
        name: "Elite",
        discount: 40,
        currency: 'inr',
        originalPrice: 916,
        pricePerUser: 550,
        billing_cycle: 'yearly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Recorded Screen Videos",
            "Reports",
            "Attendance Tracking"
        ],
    },
    {
        id: "price_1T1kKxSZtJkrH95eEELZw0G3",
        name: "Elite",
        discount: 40,
        currency: 'usd',
        originalPrice: 916,
        pricePerUser: 7.20,
        billing_cycle: 'yearly',
        members_text: 'Unlimited Team Members',
        features: [
            "Unlimited Workspace",
            "Unlimited Projects",
            "Unlimited Tasks",
            "Unlimited Workflows",
            "Time Tracking",
            "Live Screen View",
            "Screenshots",
            "Recorded Screen Videos",
            "Reports",
            "Attendance Tracking"
        ],
    }
    ]
};


export const planNames =  {
    'price_1T1kHASZtJkrH95eQL9A6yDo': 'Pro',
    'price_1T1kHcSZtJkrH95eh134b9bb': 'Pro',
    'price_1T1kHsSZtJkrH95en1y7PPEF': 'Pro',

    'price_1T1kI7SZtJkrH95e0GJmug6u': 'Pro',
    'price_1T1kIPSZtJkrH95eeutEK3Ju': 'Pro',
    'price_1T1kIlSZtJkrH95eQ5T5a2OD': 'Pro',

    'price_1T1kKxSZtJkrH95e14uVND57': 'Elite',
    'price_1T1kKxSZtJkrH95etWdAjHqI': 'Elite',
    'price_1T1kKxSZtJkrH95eJMnYM4aa': 'Elite',

    'price_1T1kKxSZtJkrH95ehbhfAbCK': 'Elite',
    'price_1T1kKxSZtJkrH95e27mYWXim': 'Elite',
    'price_1T1kKxSZtJkrH95eEELZw0G3': 'Elite',
    'free': 'Free',
    'trial': 'Trial'
}

export const planPrices =  {
    'price_1T1kHASZtJkrH95eQL9A6yDo': 66600,
    'price_1T1kHcSZtJkrH95eh134b9bb': 53300,
    'price_1T1kHsSZtJkrH95en1y7PPEF': 40000,

    'price_1T1kI7SZtJkrH95e0GJmug6u': 800,
    'price_1T1kIPSZtJkrH95eeutEK3Ju': 640,
    'price_1T1kIlSZtJkrH95eQ5T5a2OD': 480,

    'price_1T1kKxSZtJkrH95e14uVND57': 91600,
    'price_1T1kKxSZtJkrH95etWdAjHqI': 55000,
    'price_1T1kKxSZtJkrH95eJMnYM4aa': 73300,

    'price_1T1kKxSZtJkrH95ehbhfAbCK': 1200,
    'price_1T1kKxSZtJkrH95e27mYWXim': 960,
    'price_1T1kKxSZtJkrH95eEELZw0G3': 720,

    'free': 0,
    'trial': 0
}