// export const plans = {
//     'monthly':[
//     {
//     id: "free",
//     name: "Free",
//     originalPrice: 0,
//     pricePerUser: 0,
//     discount: 0,
//     billing_cycle: false,
//     members_text: 'Free for up to 3 members',
//     features: [
//         "Single Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     },
//     {
//     id: "price_1Sm6f9SZtJkrH95eY3adt6dK",
//     name: "Pro",
//     originalPrice: 666,
//     pricePerUser: 666,
//     discount: 0,
//     billing_cycle: 'monthly',
//     members_text: 'Unlimited Team Members',
//     features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     },
//     {
//     id: "price_1Sm6h8SZtJkrH95eYrwqvWQx",
//     name: "Elite",
//     discount: 0,
//     originalPrice: 916,
//     pricePerUser: 916,
//     billing_cycle: 'monthly',
//     members_text: 'Unlimited Team Members',
//     features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Recorded Screen Videos",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     }],
//     'quarterly':[
//     {
//     id: "free",
//     name: "Free",
//     originalPrice: 0,
//     pricePerUser: 0,
//     discount: 0,
//     billing_cycle: false,
//     members_text: 'Free for up to 3 members',
//     features: [
//         "Single Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     },
//     {
//     id: "price_1Sm6g9SZtJkrH95efBqhCMs0",
//     name: "Pro",
//     discount: 20,
//     originalPrice: 666,
//     pricePerUser: 533,
//     billing_cycle: 'quarterly',
//     members_text: 'Unlimited Team Members',
//     features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     },{
//     id: "price_1Sm6hSSZtJkrH95e3ouAIMxd",
//     name: "Elite",
//     discount: 20,
//     originalPrice: 916,
//     pricePerUser: 733,
//     billing_cycle: 'quarterly',
//     members_text: 'Unlimited Team Members',
//     features: [
//     "Unlimited Workspace",
//     "Unlimited Projects",
//     "Unlimited Tasks",
//     "Unlimited Workflows",
//     "Time Tracking",
//     "Live Screen View",
//     "Screenshots",
//     "Recorded Screen Videos",
//     "Reports",
//     "Attendance Tracking"
//     ],
//     }],
//     'yearly': [
//     {
//     id: "free",
//     name: "Free",
//     pricePerUser: 0,
//     discount: 0,
//     billing_cycle: false,
//     members_text: 'Free for up to 3 members',
//     features: [
//         "Single Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     },{
    
//     id: "price_1Sm6gZSZtJkrH95eBNmdopyx",
//     name: "Pro",
//     discount: 40,
//     originalPrice: 666,
//     pricePerUser: 400,
//     billing_cycle: 'yearly',
//     members_text: 'Unlimited Team Members',
//     features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     },{
//     id: "price_1Sm6hhSZtJkrH95e3hAKkKBG",
//     name: "Elite",
//     discount: 40,
//     originalPrice: 916,
//     pricePerUser: 550,
//     billing_cycle: 'yearly',
//     members_text: 'Unlimited Team Members',
//     features: [
//         "Unlimited Workspace",
//         "Unlimited Projects",
//         "Unlimited Tasks",
//         "Unlimited Workflows",
//         "Time Tracking",
//         "Live Screen View",
//         "Screenshots",
//         "Recorded Screen Videos",
//         "Reports",
//         "Attendance Tracking"
//     ],
//     }]
// };


export const plans = {
    'monthly':[
    {
    id: "free",
    name: "Free",
    originalPrice: 0,
    pricePerUser: 0,
    discount: 0,
    billing_cycle: false,
    members_text: 'Free for up to 3 members',
    features: [
        "Single Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Reports",
        "Attendance Tracking"
    ],
    },
    {
    id: "price_1Sd5xOSZtJkrH95e6De3lu49",
    name: "Pro",
    originalPrice: 666,
    pricePerUser: 666,
    discount: 0,
    billing_cycle: 'monthly',
    members_text: 'Unlimited Team Members',
    features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Reports",
        "Attendance Tracking"
    ],
    },
    {
    id: "price_1Sd5xcSZtJkrH95eunkuqn5L",
    name: "Elite",
    discount: 0,
    originalPrice: 916,
    pricePerUser: 916,
    billing_cycle: 'monthly',
    members_text: 'Unlimited Team Members',
    features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Recorded Screen Videos",
        "Reports",
        "Attendance Tracking"
    ],
    }],
    'quarterly':[
    {
    id: "free",
    name: "Free",
    originalPrice: 0,
    pricePerUser: 0,
    discount: 0,
    billing_cycle: false,
    members_text: 'Free for up to 3 members',
    features: [
        "Single Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Reports",
        "Attendance Tracking"
    ],
    },
    {
    id: "price_1Sd61mSZtJkrH95eF1JYfDT8",
    name: "Pro",
    discount: 20,
    originalPrice: 666,
    pricePerUser: 533,
    billing_cycle: 'quarterly',
    members_text: 'Unlimited Team Members',
    features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Reports",
        "Attendance Tracking"
    ],
    },{
    id: "price_1Sm7ybSZtJkrH95ejSuFgBwz",
    name: "Elite",
    discount: 20,
    originalPrice: 916,
    pricePerUser: 733,
    billing_cycle: 'quarterly',
    members_text: 'Unlimited Team Members',
    features: [
    "Unlimited Workspace",
    "Unlimited Projects",
    "Unlimited Tasks",
    "Unlimited Workflows",
    "Time Tracking",
    "Live Screen View",
    "Screenshots",
    "Recorded Screen Videos",
    "Reports",
    "Attendance Tracking"
    ],
    }],
    'yearly': [
    {
    id: "free",
    name: "Free",
    pricePerUser: 0,
    discount: 0,
    billing_cycle: false,
    members_text: 'Free for up to 3 members',
    features: [
        "Single Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Reports",
        "Attendance Tracking"
    ],
    },{
    
    id: "price_1Sm7xbSZtJkrH95e4Vo7M7xx",
    name: "Pro",
    discount: 40,
    originalPrice: 666,
    pricePerUser: 400,
    billing_cycle: 'yearly',
    members_text: 'Unlimited Team Members',
    features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Reports",
        "Attendance Tracking"
    ],
    },{
    id: "price_1Sm7ymSZtJkrH95eeInuKZel",
    name: "Elite",
    discount: 40,
    originalPrice: 916,
    pricePerUser: 550,
    billing_cycle: 'yearly',
    members_text: 'Unlimited Team Members',
    features: [
        "Unlimited Workspace",
        "Unlimited Projects",
        "Unlimited Tasks",
        "Unlimited Workflows",
        "Time Tracking",
        "Live Screen View",
        "Screenshots",
        "Recorded Screen Videos",
        "Reports",
        "Attendance Tracking"
    ],
    }]
};