import React, { useEffect, useState, useRef } from 'react';
import { useDispatch, useSelector } from "react-redux";
import { Button, Modal, Form, ListGroup, FloatingLabel, Row, Col, InputGroup, Dropdown, ListGroupItem, Image} from "react-bootstrap";

import { updateStateData, togglePopups } from '../../redux/actions/common.action';
import { TASK_FORM, RESET_FORMS, ACTIVE_FORM_TYPE, CURRENT_TASK } from '../../redux/actions/types';
import { FiFileText } from "react-icons/fi";
import { GrAttachment } from "react-icons/gr";
import { FaPaperPlane, FaRegCalendarAlt } from "react-icons/fa";
import { BiSolidPencil } from "react-icons/bi";
import { GrDrag } from "react-icons/gr";
import { LuWorkflow } from "react-icons/lu";
import { FilesPreviewModal } from '../modals';
import { getFieldRules, validateField } from '../../helpers/rules';
import { updateTask, deleteTask } from '../../redux/actions/task.action';
import { socket, SendComment, DeleteComment, UpdateComment } from '../../helpers/auth';
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
import { MemberInitials } from '../common/memberInitials';
import DatePicker from "react-multi-date-picker";
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';